Map<String, String> enLang = {
  'appName' : 'Tucktek',
  'Explore' : 'Explore',
  'Community' : 'Community',
  'Navigate' : 'Navigate',
  'Saved' : 'Saved',
  'Save' : 'Save',
  'Profile' : 'Profile',
  'Edit' : 'Edit',
  'Trips' : 'Trips',
  'Photos' : 'Photos',
  'Review' : 'Review',
  'Reviews' : 'Reviews',
  'Legal' : 'Legal',
  'Support' : 'Support',
  'Account' : 'Account',
  'Cancel' : 'Cancel',
  'Camera' : 'Camera',
  'Gallery' : 'Gallery',
  'Delete' : 'Delete',
  'Star' : 'Star',
  'Direction' : 'Direction',
  'Weather' : 'Weather',
  'Daylight' : 'Daylight',
  'Sunrise' : 'Sunrise',
  'Time' : 'Time',
  'Distance' : 'Distance',
  'Continue' : 'Continue',
  'Comments' : 'Comments',
  'Create' : 'Create',
  'Closest' : 'Closest',
  'Attractions' : 'Attractions',
  'Pause' : 'Pause',
  'Finish' : 'Finish',
  'Resume' : 'Resume',
  'Rem. time' : 'Rem. time',
  'Are you sure? It will be permanently erased if you delete this activity.' : 'Are you sure? It will be permanently erased if you delete this activity.',
  'Let Use the Location Pin' : 'Let\'s Use the Location Pin',
  'You can use this location pin to find the kayaking trip path leading to the best spots for enjoying kayaking rides.' : 'You can use this location pin to find the kayaking trip path leading to the best spots for enjoying kayaking rides.',
  'Location Pin' : 'Location Pin',
  'Delete activity' : 'Delete activity',
  'Apply Filter' : 'Apply Filter',
  '0 km' : '0 km',
  'Newly Address' : 'Newly Address',
  'Most Popular' : 'Most Popular',
  'Best Match' : 'Best Match',
  'Activity Saved' : 'Activity Saved',
  'Check it out' : 'Check it out',
  'Stay connected, inspired, and discover more.' : 'Stay connected, inspired, and discover more.',
  'More to come' : 'More to come',
  'Encourage friends' : 'Encourage friends',
  'Like the view? Let them know!' : 'Like the view? Let them know!',
  'Discover new kayaking spots.' : 'Discover new kayaking spots.',
  'Get Inspired' : 'Get Inspired',
  'Meet our new space: where human connections meets Kayaking spots inspiration.' : 'Meet our new space: where human connections meets Kayaking spots inspiration.',
  'Welcome to Community' : 'Welcome to Community',
  'Share Kayak Spot' : 'Share Kayak Spot',
  'and thanks for taking us with you! Let do it again soon.' : 'and thanks for taking us with you! Let\'s do it again soon.',
  'Way to get out there' : 'Way to get out there',
  'Please wait a moment kayaking spots loading...' : 'Please wait a moment kayaking spots loading...',
  'Kayaking Spots' : 'Kayaking Spots',
  'swipe down to see the map' : 'swipe down to see the map',
  'People reviews' : 'People\'s reviews',
  'You can add photos and videos up to 10' : 'You can add photos and videos up to 10',
  'Add photos and videos' : 'Add photos and videos',
  'Create Post' : 'Create Post',
  'Create first post' : 'Create first post',
  'Let begin sharing posts in the community with your first post' : 'Let\'s begin sharing posts in the community with your first post',
  'There are no community post yet' : 'There are no community post yet',
  'Add your comments...' : 'Add your comments...',
  'I would like to hear your thoughts on getting the party started.' : 'I would like to hear your thoughts on getting the party started.',
  'There are no comments yet' : 'There are no comments yet',
  'You will no longer be able to see this user or their content' : 'You will no longer be able to see this user or their content',
  'Thank you for letting us know' : 'Thank you for letting us know',
  'Send Kayak Invite' : 'Send Kayak Invite',
  'Please note : Kayak Invite will be sent to all Tecktec users within a 10 mile radius of your location, and you can send them one at a time.' : 'Please note : Kayak Invite will be sent to all Tecktec users within a 10 mile radius of your location, and you can send them one at a time.',
  'Date and time' : 'Date and time',
  'Kayaking spot location' : 'Kayaking spot location',
  'Invite Description' : 'Invite Description',
  'Kayaking spot name' : 'Kayaking spot name',
  'Enter kayaking spot name' : 'Enter kayaking spot name',
  'Write your thought about this kayaking spots...' : 'Write your thought about this kayaking spots...',
  'Kayak Invite' : 'Kayak Invite',
  'Enter name of your kayaking spot' : 'Enter name of your kayaking spot',
  'Let add some photos and videos' : 'Let\'s add some photos and videos',
  'Name your kayaking spot' : 'Name your kayaking spot',
  'Description kayaking spot' : 'Description kayaking spot',
  'Let other people know about your kayaking experience' : 'Let other people know about your kayaking experience',
  'Avg. speed' : 'Avg. speed',
  'Trip linked to' : 'Trip linked to',
  'UV Index' : 'UV Index',
  'Attractions' : 'Attractions',
  'Are you sure? These kayaking spots need to be deleted, and once they are deleted, all kayaking paths, photos, and more will be lost.' : 'Are you sure? These kayaking spots need to be deleted, and once they are deleted, all kayaking paths, photos, and more will be lost.',
  'Delete Kayaking Spots' : 'Delete Kayaking Spots',
  'Review this kayaking spot' : 'Review this kayaking spot',
  'People reviews this kayaking spot' : 'People\'s reviews this kayaking spot',
  'People rate this kayaking spot' : 'People\'s rate this kayaking spot',
  'See all reviews' : 'See all reviews',
  'Description' : 'Description',
  'People rate & reviews' : 'People\'s rate & reviews',
  'Photos and Videos' : 'Photos and Videos',
  'Kayaking Path' : 'Kayaking Path',
  'My Kayak Spots' : 'My Kayak Spots',
  'My Trips' : 'My Trips',
  'My Favorites' : 'My Favorites',
  'Yes, Delete Account' : 'Yes, Delete Account',
  'Are you sure you want to permanently delete this account, after deleting this account you will lose all your Trips, Kayak spots, community posts, photos, reviews, and more.' : 'Are you sure you want to permanently delete this account, after deleting this account you will lose all your Trips, Kayak spots, community posts, photos, reviews, and more.',
  'Delete the account permanently?' : 'Delete the account permanently?',
  'Here are some of the most frequently asked questions' : 'Here are some of the most frequently asked questions',
  'How can we help you?' : 'How can we help you?',
  'FAQ' : 'FAQ\'s',
  'Kayaking is a popular sport among many people. What should others know about it?' : 'Kayaking is a popular sport among many people. What should others know about it?',
  'Nice-5 starts! Cant get any better than that' : 'Nice-5 starts! Can\'t get any better than that!',
  'Share your kayaking experience to help others plan their next trip' : 'Share your kayaking experience to help others plan their next trip',
  'I would appreciate if you reviewed any kayaking spots. Your review will appear here once you have reviewed it' : 'I would appreciate if you reviewed any kayaking spots. Your review will appear here once you have reviewed it',
  'There has not been a review yet' : 'There has not been a review yet',
  'rate & reviews' : ') rate & reviews',
  'Yes, Delete' : 'Yes, Delete',
  'Are you sure you want to permanently delete this photo?' : 'Are you sure you want to permanently delete this photo?',
  'Delete photo' : 'Delete photo',
  'No photos upload yet' : 'No photos upload yet',
  'New Password' : 'New Password',
  'Old Password' : 'Old Password',
  'Change Password' : 'Change Password',
  'Edit Profile' : 'Edit Profile',
  'Upload profile picture' : 'Upload profile picture',
  'App version :' : 'App version :',
  'Log out' : 'Log out',
  'Share App' : 'Share App',
  'Share' : 'Share',
  'Yes, Log out' : 'Yes, Log out',
  'Are you sure you want to log out of the Tecktech app on this device?' : 'Are you sure you want to log out of the Tecktech app on this device?',
  'Delete the account permanently' : 'Delete the account permanently',
  'Share your friends and family' : 'Share your friends and family',
  'Enjoying app Rate us' : 'Enjoying app Rate us',
  'Email us' : 'Email us',
  'FAQ' : 'FAQ\'s',
  'Terms of services' : 'Terms of services',
  'Privacy Policy' : 'Privacy Policy',
  'About us' : 'About us',
  'Community Post' : 'Community Post',
  'Kayak Spots' : 'Kayak Spots',
  'Post' : 'Post',
  'Take a kayaking tour' : 'Take a kayaking tour',
  'See All' : 'See All',
  'Take a look now' : 'Take a look now',
  'discover' : 'Discover',
  'intro_subtitle' : 'The World With\nOur Folding Kayaks\nAnd See The Difference',
  'Get Started' : 'Get Started ↗',
  'New to Tucktec?' : 'New to Tucktek? ',
  'Log in' : 'Log in',
  'Send email' : 'Send email →',
  'Start' : 'Start',
  'Skip Now' : 'Skip Now',
  'Register' : 'Register',
  'First name' : 'First name',
  'Last name' : 'Last name',
  'Email address' : 'Email address',
  'Create Password' : 'Create Password',
  'Enter your first name' : 'Enter your first name',
  'Enter your last name' : 'Enter your last name',
  'Enter your email address' : 'Enter your email address',
  'By counting to use Tucktec, you agree to our' : 'By counting to use Tucktek, you agree to our ',
  'Terms of Services' : 'Terms of Services ',
  'and' : 'and ',
  'Privacy Policy.' : 'Privacy Policy.',
  'Already Tucktec Account?' : 'Already Tucktek Account? ',
  'Welcome back. Log in' : 'Welcome back.\nLog in',
  'Forgot your password?' : 'Forgot your password?',
  'Reset your password' : 'Reset your\npassword',
  'We will send you an email to reset your password.' : 'We will send you an email to reset your password.',
  'Open email' : 'Open email →',
  'Check your email' : 'Check your\nemail',
  'We sent an email to' : 'We sent an email to\n',
  'to help you log in. Follow the email prompt to continue.' : ' to help you log in. Follow the email prompt to continue.',
  'Search kayaking spots' : 'Search kayaking spots',
  'See all' : 'See all',

  // exception
  'something_went_wrong' : 'Unfortunately, something went wrong',
  'no_internet_connection' : 'No Internet Connection',
  'access_denied' : 'Access Denied',
  'server_error' : 'Server Error',
  'connection_timeout_exception' : 'Connection Time Out',
  'explore_no_item_title' : 'Unavailable kayaking spots at the moment',
  'explore_no_item_subtitle' : 'In a few minutes you will have kayaking spots at your fingertips. You can shop for folding kayaks on our website foldupkayaks.com'
};
