/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String aboutBodyShape = "assets/images/aboutBodyShape.png";
  static const String aboutDrink = "assets/images/aboutDrink.png";
  static const String aboutEducation = "assets/images/aboutEducation.png";
  static const String aboutHighte = "assets/images/aboutHighte.png";
  static const String aboutHome = "assets/images/aboutHome.png";
  static const String aboutKids = "assets/images/aboutKids.png";
  static const String aboutLanguage = "assets/images/aboutLanguage.png";
  static const String aboutReligious = "assets/images/aboutReligious.png";
  static const String aboutSearch = "assets/images/aboutSearch.png";
  static const String aboutSmoke = "assets/images/aboutSmoke.png";
  static const String apple = "assets/images/apple.png";

  static const String back = "assets/images/back.png";

  static const String background = "assets/images/background.png";
  static const String background1 = "assets/images/background1.png";

  static const String blockIcon = "assets/images/blockIcon.png";
  static const String boosterYellow = "assets/images/boosterYellow.png";
  static const String calendar = "assets/images/calendar.png";

  static const String callRed = "assets/images/callRed.png";
  static const String camera = "assets/images/camera.png";
  static const String cameraIcon = "assets/images/cameraIcon.png";
  static const String cancel = "assets/images/cancel.png";
  static const String caution = "assets/images/caution.png";

  static const String checkBoxRectanggle =
      "assets/images/checkBoxRectanggle.png";
  static const String checked = "assets/images/checked.png";
  static const String checkWithoutBg = "assets/images/checkWithoutBg.png";
  static const String childern = "assets/images/childern.png";
  static const String cigrate = "assets/images/cigrate.png";
  static const String circleWithColored = "assets/images/circleWithColored.png";
  static const String circleWithoutColred =
      "assets/images/circleWithoutColred.png";

  static const String cross = "assets/images/cross.png";
  static const String crownImage = "assets/images/crownImage.png";
  static const String currentLocationIcon =
      "assets/images/currentLocationIcon.png";

  static const String deleteIcon = "assets/images/deleteIcon.png";
  static const String deleteWithouBackground =
      "assets/images/deleteWithouBackground.png";
  static const String drink = "assets/images/drink.png";
  static const String dropIcon = "assets/images/dropIcon.png";

  static const String editProfile = "assets/images/editProfile.png";

  static const String facebook = "assets/images/facebook.png";
  static const String facebookRoundImage =
      "assets/images/facebookRoundImage.png";

  static const String filterIcon = "assets/images/filterIcon.png";
  static const String forward = "assets/images/forward.png";

  static const String gallery = "assets/images/gallery.png";
  static const String gmail = "assets/images/gmail.png";
  static const String google = "assets/images/google.png";

  static const String heartBlack = "assets/images/heartBlack.png";
  static const String heightIcon = "assets/images/heightIcon.png";

  static const String home = "assets/images/home.png";

  static const String iconSingleCheck = "assets/images/iconSingleCheck.png";

  static const String instagram = "assets/images/instagram.png";
  static const String intro1 = "assets/images/intro1.png";
  static const String intro2 = "assets/images/intro2.png";
  static const String intro3 = "assets/images/intro3.png";
  static const String intro_4 = "assets/images/intro_4.png";

  static const String locationIcon = "assets/images/locationIcon.png";

  static const String man = "assets/images/man.png";

  static const String messageRedIcon = "assets/images/messageRedIcon.png";
  static const String moreIcon = "assets/images/moreIcon.png";

  static const String notification = "assets/images/notification.png";
  static const String online = "assets/images/online.png";
  static const String other = "assets/images/other.png";
  static const String payPal = "assets/images/payPal.png";
  static const String profileIcon = "assets/images/profileIcon.png";
  static const String profileIntro = "assets/images/profileIntro.png";
  static const String redHeartImage = "assets/images/redHeartImage.png";
  static const String redHeartWithWhiteBackground =
      "assets/images/redHeartWithWhiteBackground.png";
  static const String redHeartWithWhiteBackground1 =
      "assets/images/redHeartWithWhiteBackground1.png";

  static const String rightArrowIcon = "assets/images/rightArrowIcon.png";
  static const String rightRedIcon = "assets/images/rightRedIcon.png";
  static const String rightSignGray = "assets/images/rightSignGray.png";
  static const String rightSignWhite = "assets/images/rightSignWhite.png";
  static const String send = "assets/images/send.png";

  static const String setting = "assets/images/setting.png";

  static const String splashLogo = "assets/images/splashLogo.png";
  static const String star = "assets/images/star.png";

  static const String stripe = "assets/images/stripe.png";

  static const String switchButtonGray = "assets/images/switchButtonGray.png";
  static const String swithButtonRed = "assets/images/swithButtonRed.png";
  static const String unchecked = "assets/images/unchecked.png";
  static const String upgrade = "assets/images/upgrade.png";

  static const String videoRed = "assets/images/videoRed.png";
  static const String woman = "assets/images/woman.png";

  static const String dashboardPic = "assets/images/dashboard_image.jpeg";
  static const String bannerImages = "assets/images/viveImages.png";
  static const String featureGraphic = "assets/images/feature_graphic.jpg";
  static const String iconMusicSystem = "assets/images/icon_music_system.jpeg";
}
